name: tests

on:
  push:
    branches:
      - main
  pull_request: []

jobs:
  lint:
    name: 📄 Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          use-only-tar-bz2: false # required for caching
          show-channel-urls: true
          channel-priority: strict
          activate-environment: mpp-dev
          environment-file: tests/environment-dev.yml

      - name: Install mpp-dev
        run: |
          conda activate mpp-dev
          python setup.py install
          conda list
          conda info --all

      - name: Lint code
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
          # pydocstyle ./src
      - name: Test docs
        run: make -C ./docs html

  test:
    name: 🧪 Testing
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          use-only-tar-bz2: false # required for caching
          show-channel-urls: true
          channel-priority: strict
          activate-environment: mpp-dev
          environment-file: tests/environment-dev.yml

      - name: Install mppshared
        run: |
          conda activate mpp-dev
          python setup.py install
          conda list
          conda info --all

      - name: Unit Tests
        id: unit-tests
        run: |
          conda activate mpp-dev
          which conda
          which python
          coverage run --source ./src --module pytest --verbose
          coverage xml -i
          coverage report -m
